spring:
  kafka:
    bootstrap-servers: http://kafka.qa-aws.intranet.pagseguro.uol:9092
    properties:
      schema:
        registry:
          url: http://schema-registry.qa-aws.intranet.pagseguro.uol:8081
